### ISSUE TITLE
Error 500 when starting

### ISSUE THREAD

**Issue by flavienbwk** [didin1453fatih/dbdesigner.id#13]
Hi,

I encounter this problem when running `npm run serve` on the web interface : 
![image](https://user-images.githubusercontent.com/14158127/71693837-c1121000-2dad-11ea-82ed-9a7e4a376921.png)

Endpoint : `http://localhost:8081/back-office/api/v1/account/read`
Error : `Proxy error: Could not proxy request /back-office/api/v1/account/read from localhost:8081 to http://localhost:81 (ECONNREFUSED).`

Thanks for the help

**Comment by gramlin** [comment]
Looks like the backend is missing as there is no src for /back-office/ in the github project.

**Comment by flavienbwk** [comment]
Thanks @gramlin, so there's no workaround ? This project is unusable ?

**Comment by didin1453fatih** [comment]
@flavienbwk @gramlin  This is problem in backend. and this directory place in another sub module repo.  Now i was refactoring this repository structure to be easy to clone and run in your private server. I change database from mysql to be sqlite for easy instalation.
![image](https://user-images.githubusercontent.com/38158591/85305229-faaf1280-b4d6-11ea-9636-7826ee1c7db9.png)

**Comment by gramlin** [comment]
Great. Thanks! :)
