### ISSUE TITLE
sqlite support

### ISSUE THREAD

**Issue by DickerPeter** [didin1453fatih/dbdesigner.id#16]
by when is it planned to support the sqlite?

**Comment by flavienbwk** [comment]
@DickerPeter Did you even managed to connect to a back-end ? I'm stuck with error 500 because there's no `back-office` folder in this Github project.

**Comment by DickerPeter** [comment]
actually I wanted to ask if something is planned.  because I would find this useful

**Comment by didin1453fatih** [comment]
@DickerPeter  Yes, now https://dbdesigner.id support sqlite as database backend.  This is make easy install to your own server. I follow this method like https://github.com/TryGhost/Ghost.
Thank you...

**Comment by didin1453fatih** [comment]
@DickerPeter  sorry about this trouble. I don't have time to fixing it. Now this issue about error 500 was fixed. Database change from mysql to be sqlite.
Thank you...
