### ISSUE TITLE
Remove or comment out Google Tags/UA info from source

### ISSUE THREAD

**Issue by matrixes** [didin1453fatih/dbdesigner.id#34]
I can understand the need/want to track usage on a centrally hosted server for you as the code repository owner.

However, unless this can be easily overridden or if you have an intention to fully disclose the metrics collected or if you explain clearly what you intend to do with the data and how to easily remove it, I'd personally request this be removed or commented out from the source.

**Comment by didin1453fatih** [comment]
https://github.com/didin1453fatih/dbdesigner.id/commit/70b547a80851e6b59ac22cea6177501e037ba43d

This issue fixed in latest
