### ISSUE TITLE
Increase allowed POST payload size

### ISSUE THREAD

**Issue by matrixes** [didin1453fatih/dbdesigner.id#35]
In the current implementation I got hit with a `PayLoadTooLargeError` that didn't become apparent until I reloaded one of my diagrams and I had lost a big chunk of my work.

This is what I did, in my own local environment, to make things work again:

```
diff --git a/backend/extension/core/event/onWebBeforeLoad.event.js b/backend/extension/core/event/onWebBeforeLoad.event.js
index a8e0211..527b3a0 100644
--- a/backend/extension/core/event/onWebBeforeLoad.event.js
+++ b/backend/extension/core/event/onWebBeforeLoad.event.js
@@ -44,7 +44,7 @@ module.exports = {
 
     await app.use(bodyParser.urlencoded({ extended: false }));
     console.log("ON yyy");
-    await app.use(bodyParser.json());
+    await app.use(bodyParser.json({limit: '100Mb'}));
     await app.use(bearerToken({
       headerKey: 'Bearer'
     }));
```
The change I did to the code isn't someting I recommend for anything going into production. I just set it to a very high value to avoid issues with this in the future.

**Comment by didin1453fatih** [comment]
This fixed thanks for review this code.
https://github.com/didin1453fatih/dbdesigner.id/commit/6f6e7a4303d917246d3d558ee4ded794c95760e6
