### ISSUE TITLE
Save Failure With Status Code 502

### ISSUE THREAD

**Issue by Alangkibar** [didin1453fatih/dbdesigner.id#37]
Everytime my project saving, it always return 502 and I can't continue my work now

**Comment by mihai-fologea** [comment]
I have the same problem and I think it's occurring because of the issue described in #35

**Comment by myindexlike** [comment]
Doesn't save - produces 502
When I open it in a separate tab, it shows the old save.

**Comment by didin1453fatih** [comment]
Related this issue.
https://github.com/didin1453fatih/dbdesigner.id/issues/35
